### PR TITLE
Add condition to link definition.

### PR DESCRIPTION
**Pull request by manuel-guilbault**
Add the possibility to make a link conditional to the resource state.

### CODE REVIEW

**Comment by manuel-guilbault** [comment]
@faniereynders sure :)

One of the main interest of HATEOAS is to move knowledge about the system from the client to the server, right? To reduce the amount of business/domain knowledge the client has? With that intent in mind, making some links conditional to some state condition allows to move the knowledge about operation availability from the client to the server. This way, the client just relies on the fact that a link is there or not to know if an operation is available for the resource. It allows to decouple clients from domain knowledge, and to more easily change the conditions that make an operation available without having to change the clients.

I modified the sample project to illustrate just that. I added an `IsReadOnly` property to the `PersonDto` class, and made the `update-person` and `delete-person` links conditional to the `IsReadOnly` property being `true`. This means that if you create a `Person` with the `IsReadOnly` property to `true`, the `update-person` and the `delete-person` links won't be found in this person's resource list of links. Clients don't know why the links are there or not. They don't know that a read-only person cannot be updated or deleted. They just know that they can't try to update or delete a person if the proper links are not on the resource.

**Comment by faniereynders** [comment]
Thank you for that detailed explanation. The scenario you mentioned is valid, however what should happen in a scenario when a user IS able to update/delete a resource? Will the `readonly` flag be `false` in that case? Also, including a flag as part of the DTO payload seems a bit strange, I could see it rather be optionally part of the HATEOAS wrapper abstract class `Resource`.

I think you are on to something here, but think we should also make it a bit more flexible in a sense by passing in some sort of context for the condition so that other things could also be validated like user claims for instance.

Does that make sense?

**Comment by manuel-guilbault** [comment]
If the user should be able to update/delete a resource, then the `IsReadOnly` property will be `false`, yes. In fact, `IsReadOnly` is just an example here. The idea is just to allow links to be conditional to some resource state.

Allowing to make a link conditional to some other context data (like user claims) is also a valid use case. Let me wrap up my reasoning in another post :)

**Comment by manuel-guilbault** [comment]
My goal with this pull request was to add the possibility to kind of disable links in the less intrusive way possible :) But I absolutely agree with your points. Let me summarize and elaborate.

## Types of condition

When deciding if a link should be there or not, I see 3 types of condition:

1. The condition uses some context data (e.g.: user claims, or an object resolved from the ServiceProvider). The current pull request doesn't address this, as you pointed out in a comment.
2. The condition uses value(s) from the underlying domain object/read model/entity (whatever term you prefer - I'll use the word entity for brevity). The current pull request does this using the actual DTO returned by the controller action method, as there's currently no way it can access the original entity before it was mapped to the DTO. I elaborate on this issue below.
3. The condition uses a combination of the two first types.

I think we can address the three points by using a predicate that receives both the DTO/entity and the `HttpContext` as parameters:

```csharp
services
    .AddMvc()
    .AddHateoas(options =>
    {
        options
            // other links...
           .AddLink<PersonDto>(
                "update-person",
                p => new { id = p.Id },
                condition: (p, httpContext) => !p.IsReadOnly);
    });
```

Since the `HttpContext` gives access to pretty much everything related to the current HTTP request, including the `IServiceProvider` (through its `RequestServices` property) and the (potentially) logged-in user, I think it is the best contextual object to pass to the condition lambda expression.

## The entity vs DTO problem

Most of the time, controller action methods return DTOs that are mapped from entities (or other business/domain artifacts). Ideally, knowledge about operation conditions should belong to those entities, not to DTOs. As such, link condition lambda expressions should ideally operate on entities, not on DTOs.

I see two solutions to this problem, each with their own pros & cons.

### 1. Make the HATEOAS plugin handle the mapping from entity to DTO

In order to be able to pass original entities to condition lambda expressions, a controller action method must return the original entity, not a DTO. This means the link declaration API should be modified to tell the HATEOAS plugin on which DTO type it should map the entity and how it should do it.

#### Example

Let's imagine the following domain object:

```csharp
public class Person
{
    public int Id { get; }
    public string Name { get; }
    public string Email { get; }

    public bool CanBeUpdatedBy(ClaimsPrincipal user) => user.IsInRole("some-role");
}
```

With the following corresponding DTO:

```csharp
public class PersonDto
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
}
```

Now let's see how a conditional link would be added:

```csharp
services
    .AddMvc()
    .AddHateoas(options =>
    {
        options
            .AddEntity<Person>(builder =>
            {
                builder
                    .MapToDto(entity => new PersonDto
                    {
                        Id = entity.Id,
                        // other properties...
                    })
                    // other links...
                    .AddLink(
                        "update-person",
                        p => new { id = p.Id },
                        condition: (p, httpContext) => p.CanBeUpdatedBy(httpContext.User));
            });
    });
```

This means the controller action method would look like this:

```csharp
[Route("api/[controller]")]
public class PeopleController : Controller
{
    [HttpGet("{id}", Name = "get-person")]
    public IActionResult Get(IPersonRepository repository, int id) {
        var person = repository.GetPersonById(id);
        return Ok(person);
    }

    // other methods...
}
```

Notice how the action method now returns the original entity instead of a DTO.

#### Pros & cons

This leaves the DTO unchanged and clean from any other concerns.

However, it moves the responsibility of mapping an entity to its DTO into the HATEOAS plugin, which feels weird to me. It also makes the declaration of links much more complicated, and makes it much harder to reason about how the plugin works.

Additionally, it means that from now on, all controller action methods must return the original entity and not the DTO. First, it's a breaking change, so people already using this library will have do some work to upgrade. Second, it wouldn't be possible anymore to have multiple methods working with the same type of entity but exposing different types of DTOs (e.g.: a GET for retrieval and a POST for creation), as they all would return the same type of entity and the HATEOAS plugin wouldn't be able to tell which DTO it should map the entity to. To support this, the link declaration API would need to be added yet another information (the HTTP method in this example) in order to correctly find the DTO type and mapping to use.

Lastly, the example above performs manual mapping between the entity and the DTO. But what if users want to use something like [Automapper](https://automapper.org/)? The mapping lambda expression would need to resolve an `IMapper` instance from the service provider, then the mapping expression would need the `IServiceProvider` to be passed as an additional parameter. It makes this solution even more complicated.

### 2. Use the DTO

Use the DTO for conditions.

#### Example

Let's imagine the following domain object:

```csharp
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }

    public bool CanBeUpdatedBy(ClaimsPrincipal user) => user.IsInRole("whatever");
}
```

With the following corresponding DTO:

```csharp
public class PersonDto
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public bool IsReadOnly { get; set; }
}
```

Now let's see how a conditional link would be added:

```csharp
services
    .AddMvc()
    .AddHateoas(options =>
    {
        options
           // other links...
           .AddLink<PersonDto>(
                "update-person",
                p => new { id = p.Id },
                condition: p => !p.IsReadOnly);
    });
```

The controller action method would be unchanged. However, the mapping from the entity to the DTO would look like this:

```csharp
public PersonDto MapToDto(Person person, HttpContext httpContext)
{
    return new PersonDto
    {
        // other properties...
        IsReadOnly = !person.CanBeUpdatedBy(httpContext.User)
    };
}
```

If you don't want to expose the `IsReadOnly` flag on the resource, you can simply exclude it from serialization:

```csharp
public class PersonDto
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    [JsonIgnore] public bool IsReadOnly { get; set; }
}
```

#### Pros & cons

Declaring links stays simple and uninstrusive.

However, the DTOs get kind of polluted by link condition concerns.

## Summary

Those are the only two options I see. What do you think? If you have other ideas, I'd be happy to discuss :)

**Comment by dzmitry-lahoda** [comment]
Please merge it. I do not see sense in the project until this PR is merged. Please update `readme.md` with examples from comments.

**Comment by dzmitry-lahoda** [comment]
Will donate 13 USD for feature merged, covered by tests and docs and examples of it working with authorizeattribute roles on core 3 provided

**Comment by dzmitry-lahoda** [comment]
wow, the idea is that i could share this repo to any my aspnet colleagues so they grasp what is hateoas from readme.me easily, hence `docs and examples`

**Pull request merged**
